name: Build Plugin

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Qt
        run: |
          sudo apt-get update
          sudo apt-get install -y qt5-default qtbase5-dev
      
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make
      
      - name: Upload Plugin
        uses: actions/upload-artifact@v3
        with:
          name: AiPlugin
          path: build/libAiPlugin.plugin
